apiVersion: extensions/v1beta1
kind: Ingress
metadata:
name: microbot
spec:
rules:
- host: microbot.10.103.140.205.xip.io
    http:
    paths:
        - path: /
        backend:
            serviceName: microbot
            servicePort: 80
