apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-deployment
  labels:
    app: corc-tutorial-180417
spec:
  #Run two instances of our application
  replicas: 3
  template:
    metadata:
      labels:
        app: corc-tutorial-180417
    spec:
      #Container details
      containers:
        - name: hello-app
          image: gcr.io/corc-tutorial-180417/hello-app
          imagePullPolicy: Always
          #Ports to expose
          ports:
          - containerPort: 8000
