kind: Service
apiVersion: v1
metadata:
  #Service name
  name: hello-world-service
spec:
  selector:
    app: corc-tutorial-180417
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer